# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-23 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_todo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=512)),
                ('lastname', models.CharField(max_length=512)),
                ('email', models.CharField(max_length=512)),
                ('document', models.CharField(max_length=512)),
            ],
        ),
    ]
